### ISSUE TITLE
These requested datasets are not available from your DHS login credentials

### ISSUE THREAD

**Issue by skuchukh** [ropensci/rdhs#107]
Hello! I  would appreciate your help with this. I  have accessed HIV, SPA and survey data for all of sub-Saharan Africa. However when I  run the code (just the very last line - ARD$path), in R, it tells me that the above error message. See the code below

#' Identify datasets for these surveys
mrd <- dhs_datasets(fileType = "MR", fileFormat = "FL")[SurveyId %in% survids]
ard <- dhs_datasets(fileType = "AR", fileFormat = "FL")[SurveyId %in% survids]

#' Get local path to dataset (download if needed)
mrd$path <- unlist(get_datasets(mrd))
ard$path <- unlist(get_datasets(ard))

Thank you so much!
[Salome]([url](url
<img width="925" alt="Screen Shot 2020-09-19 at 12 11 17 PM" src="https://user-images.githubusercontent.com/70972181/93711593-8ad41680-fb1d-11ea-8e4b-8f31cf145764.png">
))

**Comment by jeffeaton** [comment]
Thanks -- the code above is not reproducible because `survids` are not defined in the code block you've posted.  But two possible leads:

1. These lines of code rely on `dhs_datasets()` returning a `data.table` object.
    ```
    mrd <- dhs_datasets(fileType = "MR", fileFormat = "FL")[SurveyId %in% survids]
    ard <- dhs_datasets(fileType = "AR", fileFormat = "FL")[SurveyId %in% survids]
    ```
    If your rdhs config is not configured to return `data.table`s, then these's lines will not return return the right thing.

    (At some point I thought it was convenient to work with `data.table` returns from the API calls, but now I tend to find them more trouble than worth and just return standard `data.frame`s.)

2) Your DHS login credentials may not be correctly saved in the rdhs config. 
     
     To test this, can you try running this to download the Angola HIV dataset?
     ```
     library(rdhs) 
     get_datasets("AOAR71FL")
     ```
     This should return the following if the download is successful:
    ```
    > get_datasets("AOAR71FL")
    $AOAR71FL
    [1] "/Users/jeff/Library/Caches/rdhs/datasets/AOAR71FL.rds"
    ```
    You can check the email address, password, and project saved in your rdhs credentials with `get_rdhs_config()`.

Thanks,
Jeff

**Comment by skuchukh** [comment]
Dear Jeff,

Thank you so much for your quick response! In response to your feedback:

1. My rdhs is config is configured to return data.tables since my code begins with 

rdhs::set_rdhs_config(data_frame = "data.table::as.data.table",
                      email = toString("my email address"),
                      project = "project name",
                      config_path = "rdhs.json",
                      global = FALSE)

2. I  ran the code below
 library(rdhs) 
get_datasets("AOAR71FL") and it gives me 

AOAR71FL
[1] "Dataset is not available with your DHS login credentials"

attr(,"reformat")
[1] FALSE

However when I  check my configuration using get_rdhs_config() my email and project name are exactly what I  have in my code. I  even copy pasted them again to make sure. 


**Please view my reproducible code below:** 

rdhs::set_rdhs_config(data_frame = "data.table::as.data.table",
                      email = toString("my email"),
                      project = "project name",
                      config_path = "rdhs.json",
                      global = FALSE)


## devtools::install_github("mrc-ide/demogsurv")
## devtools::install_github("ropensci/rdhs")

library(rdhs)
library(haven)
library(survey)
library(data.table)
library(demogsurv)
library(sf)
library(tidyverse)

# Who is running this and set working directory
id_folder <- 'sk' 

if (id_folder == 'sk') { setwd("~/ * my directory*) 

#' Identify country codes for desired countries
countries <- c("Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", 
               "Cameroon", "Central African Republic", "Chad", "Comoros", "Congo", "Congo Democratic Republic",
               "Cote d'Ivoire", "Eritrea", "Eswatini", "Ethiopia", "Gabon",
               "Gambia", "Ghana", "Guinea", "Kenya", "Lesotho", "Liberia", "Madagascar", 
               "Malawi", "Mali", "Mauritania", "Mozambique", "Namibia", "Niger",
               "Nigeria", "Nigeria (Ondo State)", "Rwanda", "Sao Tome and Principe", "Senegal",
               "Sierra Leone", "South Africa", "Sudan", "Tanzania", 
               "Togo", "Uganda", "Zambia", "Zimbabwe")
cc <- dhs_countries()[CountryName %in% countries]$DHS_CountryCode


#' Identify HIV behaviour characteristic (testing history)
survchar <- dhs_survey_characteristics()
survchar[grepl("HIV", SurveyCharacteristicName)][order(SurveyCharacteristicID)]

#' Before downloadind the individual level data, we can query the API
data_api <- dhs_data(indicatorIds = c("HA_CPHT_M_ETR", # Men ever tested for HIV and received results
                                      "HA_CPHT_M_T1R", # Men tested for HIV and received results in past 12 months
                                      "HA_PYSX_M_EPD", # Men who ever paid for sex
                                      "HA_PYSX_M_PD1"), # Men who paid for sex in the past 12 months
                     breakdown = "national", surveyYearStart = 2000)
head(data_api); dim(data_api)
length(unique(data_api$SurveyId))
# write.csv(data_api, file = "~/Desktop/data_etfsw_api.csv")

#' Identify surveys with HIV testing from desired countries
surveys <- dhs_surveys(surveyCharacteristicIds = 24, 
                       surveyYearStart = 2000, 
                       countryIds = cc,
                       surveyType = c("DHS", "AIS", "MIS"))


#' Ever tested
dat <- dhs_data(indicatorIds = c("HA_CPHT_M_ETR", # Men ever tested for HIV and received results
                                 "HA_CPHT_M_T1R", # Men tested for HIV and received results in past 12 months
                                 "HA_PYSX_M_EPD", # Men who ever paid for sex
                                 "HA_PYSX_M_PD1"), countryIds = cc, surveyYearStart = 2000) # Men who paid for sex in the past 12 months
setdiff(surveys$SurveyId, dat$SurveyId)

survids <- union(dat$SurveyId, surveys$SurveyId)

#' Identify datasets for these surveys
mrd <- dhs_datasets(fileType = "MR", fileFormat = "FL")[SurveyId %in% survids]
ard <- dhs_datasets(fileType = "AR", fileFormat = "FL")[SurveyId %in% survids]

#' Get local path to dataset (download if needed)
mrd$path <- unlist(get_datasets(mrd))
ard$path <- unlist(get_datasets(ard))

The last line still does not work unfortunately. The error code I  get: 

"These requested datasets are not available from your DHS login credentials:
---
AOAR71FL.ZIP, bfar41fl.zip, BFAR61FL.ZIP, BUAR61FL.ZIP/........etc. etc et.c "

Thank you in advance for your kind help. 

Salome

**Comment by skuchukh** [comment]
As an additional note if it helps: when I  run get_rdhs_config() I  get the following: 

 get_rdhs_config()
$email
[1] "(my email address)"

$project
[1] "(project name)"

$password
[1] "(my login password)"

$cache_path
[1] "/Users/(my name)/Library/Caches/rdhs"

$config_path
[1] "rdhs.json"

$global
[1] FALSE

$verbose_download
[1] FALSE

$verbose_setup
[1] TRUE

$timeout
[1] 30

$data_frame
function (x, keep.rownames = FALSE, ...) 
{
    if (is.null(x)) 
        return(null.data.table())
    UseMethod("as.data.table")
}
<bytecode: 0x7f96bdb22858>
<environment: namespace:data.table>

$project_choice
NULL

$data_frame_nice
[1] "data.table::as.data.table"

attr(,"class")
[1] "rdhs_config"
>

Thank you again!

**Comment by jeffeaton** [comment]
Did this resolve?

**Comment by skuchukh** [comment]
Hi Jeff

YES! I  went ahead and deleted "rdhs" folders from my chaches (in the hidden folders); uninstalled rdhs package; re-installed it and it worked!!!!  Not sure what was behind this but it does work now. 

Thank you so so much for your kind help with this!

Salome

**Comment by jeffeaton** [comment]
Great! I’m glad to hear and that’s also helpful to know what resolved it.

Thanks,
Jeff

On 23 Sep 2020, at 13:31, skuchukh <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Jeff

YES! I went ahead and deleted "rdhs" folders from my chaches (in the hidden folders); uninstalled rdhs package; re-installed it and it worked!!!! Not sure what was behind this but it does work now.

Thank you so so much for your kind help with this!

Salome
