### ISSUE TITLE
Error using get_datasets()

### ISSUE THREAD

**Issue by bstnbckr** [ropensci/rdhs#119]
This is a great package and it has been super helpful in the past! 

When attempting to download additional datasets, I get the following error message. When I first loaded the package again now, there was also a message about some changes to the API. Any ideas what might be going on here?

![image](https://user-images.githubusercontent.com/16292357/123282477-d3848a00-d50a-11eb-8445-b2bfda30d00a.png)

**Comment by jeffeaton** [comment]
I **just now** got this error as well, which I haven't seen before. I updated the package to the most recent Github version, restarted R session, and it resolved itself for me. I'm not sure what caused the error.

Could you please try installing the Github version (0.7.3) and report back if that resolves?
```
devtools::install_github("ropensci/rdhs")
```

Thanks,
Jeff

**Comment by bstnbckr** [comment]
Thanks for the quick response. I updated to version 0.7.3, now I get the following error message:
`
Downloading: 
Zimbabwe 2010 DHS Men's Recode Flat ASCII data (.dat) [ZWMR62FL.ZIP]
Logging into DHS website...
Error in unzip(tf, list = TRUE) : 
  zip file '****\AppData\Local\Temp\RtmpaMkIpM\file227c165e4e30' cannot be opened
`

**Comment by bstnbckr** [comment]
Error was caused by another package. Fixed now. Thanks!

**Comment by jeffeaton** [comment]
Great!

On Jun 24, 2021, at 17:24, bstnbckr ***@***.***> wrote:

﻿

Error was caused by another package. Fixed now. Thanks!

**Comment by chilochibi** [comment]
@bstnbckr I am getting the same error (****\AppData\Local\Temp\RtmpaMkIpM\file227c165e4e30' cannot be opened). Any chance you remember the name of the package that was causing this error.? I am running the recent version (0.74) of rdhs package
