### ISSUE TITLE
User submitted query response on how to start interacting with DHS surveys - A demo

### ISSUE THREAD

**Issue by OJWatson** [ropensci/rdhs#121]
A user provided question via email, which is being posted here for use for other individuals:

> I'm not familiar with the DHS surveys. I'm working to reproduce a methodology to calculate the wealth index from 43 DHS
surveys using 11 attributes from the household? (Rooms per person, Electricity, Floors, Water, Toilet, Phone, Radio, Tv, Car, Motorbike, Fridge). How do I select them from the surveys? 

The following is a documented answer which I hope helps show how to go about this task:

```r
library(rdhs)

# Step 0 create your config - see documentation online for how to do this correctly 
# rdhs::set_rdhs_config(...)

# Step 1 Using the API to identify surveys of interst
# first find the surveys for the countries of interest, e.g. DRC and Cote d'Ivoire  since 2010 
survs <- rdhs::dhs_surveys(countryIds = c("CD", "CI"), surveyYearStart = 2010)

# now find the actual datasets for these surveys and download the flat file format
datasets <- rdhs::dhs_datasets(surveyIds = survs$SurveyId, fileFormat = "FL")
dataset_names <- datasets$FileName[datasets$FileType == "Household Recode"]

# Now actually get these datasets by downloading them  
d <- rdhs::get_datasets(dataset_names)

# with these downloaded search for what questions are of interest
qus <- rdhs:::search_variable_labels(
  dataset_names, 
  search_terms = "Rooms|Electricity|Floors|Water|Toilet|Phone|Radio|Tv|Car|Motorbike|Fridge"
)

# from this select the specific ids that are of interest, e.g. the first 9
variables <- qus$variable[1:9]

# now search for these
vars <- rdhs:::search_variables(dataset_names, variables)

# use these to extract what you need
extract <- rdhs::extract_dhs(vars)

# and bind them together to create one dataset
# n.b. here we concatenate hv201 as it has non matching labels between the surveys
# this is flagged as a warning if you run this without the labels argument
final_df <- rdhs::rbind_labelled(extract, labels = list("hv201" = "concatenate"))
```

**Comment by kefois** [comment]
Hi, 

Is it possible to add the geographical information (lat, long) of each village (line)? 

Thank you in advance.

**Comment by OJWatson** [comment]
Hi @kefois,

Sure is.  `extract_dhs` has an option to add geographic information:

```
extract <- rdhs::extract_dhs(add_geo = TRUE)
```

That should do it

**Comment by kefois** [comment]
HI WATSON, 

Thank you.
I have this error when the downloading started:


Downloading: 
Angola 2015 DHS Household Recode Flat ASCII data (.dat) [AOHR71FL.ZIP]
Logging into DHS website...
Error in unzip(tf, list = TRUE) : 
  le fichier zip '/tmp/RtmpP2ZxP4/file19c66bd739d9' ne peut être ouvert

**Comment by kefois** [comment]
it didn't work. 
Before or after 
extract <- rdhs::extract_dhs(vars) ?

**Comment by kefois** [comment]
How can I add the lat and long?

**Comment by OJWatson** [comment]
As part of the extract call. So in the original code shared, the new extract_dhs function call would now be:

```
extract <- rdhs::extract_dhs(vars, add_geo = TRUE)
```

**Comment by kefois** [comment]
it didn't work?

**Comment by OJWatson** [comment]
You will not ensure that you have installed the `rgdal` package correctly. This often requires installing external libraries. If you have a google you will find plenty of help for correctly installing `rgdal` for your system (which i can't tell from the code you have sent)
