### ISSUE TITLE
Fix pkgdown configuration for reference

### ISSUE THREAD

**Issue by maelle** [ropensci/rdhs#135]
Some topics are missing from the configuration file.

```r
 Error in check_missing_topics(rows, pkg) : 
  All topics must be included in reference index
• Missing topics: as_factor.labelled, authenticate_dhs, available_datasets, client_cache_date, collapse_api_responses, dhs_gps_data_format, download_datasets, extraction, factor_format, file_dataset_format, get_labels_from_dataset, last_api_update, model_datasets, parse_map, rbind_list_base, rdhs, read_dhs_dataset, read_zipdata, response_is_json, response_to_json, unzip_special

```

Note that for topics you do not want to include in the index you can create an "internal" section https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#missing-topics

To check all topics are listed, after editing the configuration file you can run `pkgdown::check_pkgdown()`.

**Comment by maelle** [comment]
Thank you :smile_cat:

**Comment by OJWatson** [comment]
> Thank you 😸

Thanks very much @maelle for flagging this in the first place. Really appreciate it
