### ISSUE TITLE
get_datasets() issue 

### ISSUE THREAD

**Issue by NadineKJHA** [ropensci/rdhs#140]
Hi, just wanted to report an issue: 

dataset_names <- datasets$FileName[datasets$FileType == "Household Recode"]  #from India DHS (latest)
d <- rdhs::get_datasets(dataset_names)

_Results in the following error:_ 

Logging into DHS website...
Error in names(filedatatypelist_DHS) <- paste0("filedatatypelist_", qdapRegex::rm_between(filedatatypelist_DHS_line,  : 
  'names' attribute [17] must be the same length as the vector [1]

========
 _devtools::session_info() 
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.1 (2022-06-23)
 os       macOS Monterey 12.5.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Stockholm
 date     2022-08-27
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   NA_

**Comment by jeffeaton** [comment]
What version of rdhs are you using? Can you please try updating the package and ensure you are using a version greater than 0.7.3?

Thanks,
Jeff

**Comment by NadineKJHA** [comment]
Thank you for your quick response. I was not aware of the 0.7.5 update, which resolved the issue. Unfortunately, the particular file exhausts R's vector memory (:
