### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [ropensci/rdhs#145]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023.

rdhs imports 'rgdal'  using `rgdal::readOGR` as found by `pkgapi`, not in NAMESPACE, in R/read_datasets.R and R/shapes.R. `sf` is already suggested, so using `as(sf::st_read(), "Spatial")` is a feasible mitigation. Please fix best before June, latest October 2023.

**Comment by OJWatson** [comment]
Hi @rsbivand - thank you for the heads up. We will make the changes in May as part of our next release. 

Sorry for the delay in responding to these changes.

**Comment by rsbivand** [comment]
Excellent, thanks!

**Comment by rsbivand** [comment]
@OJWatson Did your release get delayed? Less than three months remain now.

**Comment by rsbivand** [comment]
@OJWatson @karthik @jeroen R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos.

**Comment by jeroen** [comment]
Thanks for the heads up @rsbivand. We will retire the package if we get no response from the maintainer.

**Comment by OJWatson** [comment]
@jeroen @rsbivand 

I am on it and I am working towards the deadlines you noted for CRAN removal. Thank you for the reminder and will be pushed in time before these are removed from CRAN

**Comment by rsbivand** [comment]
@OJWatson Thanks. Please let me know if I can help check a submission candidate tarball. Which branch of the repo will you be using?

**Comment by OJWatson** [comment]
Hi @rsbivand, thank you for the offer. It should be fine as i'll test the changes using Github Actions (from this PR https://github.com/ropensci/rdhs/pull/147) - this does a more thorough test than what CRAN does but once that is passing, I'll check it on rhub etc before submitting to CRAN.

**Comment by rsbivand** [comment]
@OJWatson you need to be sure that GA does not put retiring packages on the library path directly or indirectly. I certainly prefer to be closer to the metal than GA enables.

**Comment by OJWatson** [comment]
Hi @rsbivand, v0.8.0 (https://github.com/ropensci/rdhs/releases/tag/v0.8.0) has just made its way to CRAN (https://cran.r-project.org/web/packages/rdhs/index.html), which removes the spatial dependencies. 

Let me know if you have any comments and apologies for the delay with respect to the original development timelines I suggested.
