### ISSUE TITLE
don't check permission if dataset already downloaded

### ISSUE THREAD

**Issue by jeffeaton** [ropensci/rdhs#78]
All of these datasets are already downloaded from a different project than the one currently stored in my credentials. Don't check for permission if the datasets are already downloaded. 

```
These requested datasets are not available from your DHS login credentials:
---
AFIR70FL.ZIP, ALIR50FL.ZIP, ALIR71FL.ZIP, AMIR42FL.ZIP, AMIR54FL.zip, AMIR61FL.ZIP, 
...
---
Please request permission for these datasets from the DHS website to be able to download them
```

**Comment by OJWatson** [comment]
So it should first look to see if those datasets are downloaded, regardless of credentials, and that way you can still get them. Yep that seems sensible. will look into

**Comment by OJWatson** [comment]
Fixed in https://github.com/ropensci/rdhs/pull/95
