### ISSUE TITLE
Error in authentication.R

### ISSUE THREAD

**Issue by thiagomelosts** [ropensci/rdhs#87]
Just a tiny error in the code for authentication.R (lines 401 to 404): the messages for your_password and your_project are swapped:

`  # Argument Checking
  if (!is.character(your_email)) stop("your_email is not a string")
  if (!is.character(your_project)) stop("your_password is not a string")
  if (!is.character(your_password)) stop("your_project is not a string")`

Sorry if this was already pointed out, but I couldn't find any reference.

**Comment by OJWatson** [comment]
Whoops - thanks for picking this up. Will make sure to add this in the next version.
