### ISSUE TITLE
tibble issue 

### ISSUE THREAD

**Issue by OJWatson** [ropensci/rdhs#89]
If you set the default `data.frame` option to use tibbles then it breaks it, e.g.:

```
rdhs::set_rdhs_config(email,project,data_frame = "tibble::as.tibble")
ir <- get_datasets("MWIR7HFL.ZIP")[[1]] %>% readRDS
Downloading: 
NA NA NA NA NA [NA]
Error in if (file.size(tf) != desired_dataset$FileSize[1] & attempts ==  : 
  missing value where TRUE/FALSE needed
```

This breaks in `client$self$check_available_datasets()` because `datasets[,nm_type]` returns a 1 column `data.frame` rather than a vector. Just need to put a catch in here for this. 

<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>

**Comment by jeffeaton** [comment]
I'm closing this issue -- reported fixed in #95
