### ISSUE TITLE
Error on `set_rdhs_config(...)`  when writing outside R temp dir on Win10

### ISSUE THREAD

**Issue by marek-tph** [ropensci/rdhs#91]
Running the following on Windows 10:

```r
set_rdhs_config(
    email="[snip]",
    project="[snip]",
    global=FALSE,
    verbose_download=TRUE,
    data_frame="tibble::as_tibble"
)
```
and choosing option 1 (writing outside R temp directory) yields:

```
Writing your configuration to:
   -> C:\Users\kwiama\AppData\Local\kwiama\rdhs\Cache/rdhs.json

Error in file(con, "w") : cannot open the connection
In addition: Warning message:
In file(con, "w") :
  cannot open file 'C:\Users\kwiama\AppData\Local\kwiama\rdhs\Cache/rdhs.json': No such file or directory
```

The config file isn't created, nor is the rdhs cache subdirectory. The process has the rights to write to `C:\Users\kwiama\AppData\Local`, which I verified with `file.create`. Nb. other applications keep their data under `C:\Users\kwiama\AppData\Local\[app name]`, the one that is attempted here breaks the convention.

Thank you very much for this useful package.

<details> <summary><strong>Session Info</strong></summary>

```r
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252    LC_MONETARY=German_Switzerland.1252
[4] LC_NUMERIC=C                        LC_TIME=German_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rdhs_0.6.3

loaded via a namespace (and not attached):
 [1] getPass_0.2-2   compiler_3.5.1  magrittr_1.5    R6_2.4.0        tools_3.5.1     rstudioapi_0.10 rappdirs_0.3.1 
 [8] yaml_2.2.0      jsonlite_1.6    storr_1.2.1    
```
</details>

**Comment by OJWatson** [comment]
Hi again, 

My best guess is that  `C:\Users\kwiama\AppData\Local\kwiama` doesn't exist and I forgot to set `recursive = TRUE` to the directory build bits so it won'e be able to handle this. 

Thanks for flagging. 

P.S. Sorry for the delay - handing in phd thesis next month so maintenance is slipping atm :)
