### ISSUE TITLE
Error in normalizePath(path.expand(path), winslash, mustWork) 

### ISSUE THREAD

**Issue by kcsamir** [ropensci/rdhs#93]
I solved the issue.

**Comment by OJWatson** [comment]
Glad to hear it. :)

**Comment by saptahash** [comment]
Hi -- what was the solution to this? I'm facing the same issue and haven't been able to resolve it.

**Comment by saptahash** [comment]
> Hi -- what was the solution to this? I'm facing the same issue and haven't been able to resolve it.

Might have solved it, was the problem that the configs weren't set (updated in this case) and resetting them resolved this?
